#!/usr/bin/env bash
# demo.sh — end-to-end demonstration of a C++ codegen block using codegen_helper.hpp.
#
# It generates a fresh source file containing a C++ block (so the committed
# example stays pristine), runs the codegen binary on it, and prints the file
# before and after expansion.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
repo="$(cd "$here/../.." && pwd)"                 # the cpp/ directory
codegen="$repo/build/codegen"
wrapper="$here/run_cpp_block"

[ -x "$codegen" ] || { echo "build the binary first: cmake --build $repo/build" >&2; exit 1; }
chmod +x "$wrapper"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
target="$work/palette.hpp"

# A C++ block. The shebang points at the wrapper (absolute path so it resolves
# regardless of cwd). The body uses codegen_helper.hpp: it reads how many colors
# to emit from the file scope (set by an earlier block, or defaulted), emits a
# constexpr table, then records the count back into the global scope.
cat > "$target" <<EOF
#pragma once
// Auto-generated color table — edit the block, not the output.
/* CODEGEN_START
#!$wrapper
#include "codegen_helper.hpp"
#include <cstdio>
namespace cg = codegen;
int main() {
    int count = (int)cg::file().get_int("palette_size", 4);  // default 4
    std::printf("// %d entries, generated by a C++ block\n", count);
    for (int i = 0; i < count; ++i)
        std::printf("constexpr unsigned COLOR_%d = 0x%06Xu;\n", i, (i * 0x282828) & 0xFFFFFF);
    cg::global().set("last_palette_count", count);           // share with later blocks
    return 0;
}
CODEGEN_END */
EOF

echo "================ BEFORE ($target) ================"
cat "$target"
echo
echo "================ RUN ================"
echo "\$ $codegen run $target"
"$codegen" run "$target"
echo
echo "================ AFTER ================"
cat "$target"
echo
echo "================ IDEMPOTENCE CHECK ================"
before="$(cat "$target")"
"$codegen" run "$target" || true
after="$(cat "$target")"
if [ "$before" = "$after" ]; then
    echo "OK: second run left the file byte-identical (block already consumed)."
else
    echo "DIFF detected between runs:"; diff <(printf '%s' "$before") <(printf '%s' "$after") || true
fi
